#pragma once

#include "src/geometry/curve_2d.hpp"
#include "src/geometry/curve_resampler_2d.hpp"
#include "src/geometry/edge_patch_3d.hpp"
#include "src/geometry/grid_pair_2d.hpp"
#include "src/geometry/grid_pair_3d.hpp"
#include "src/geometry/nurbs_basis.hpp"
#include "src/geometry/nurbs_curve.hpp"
#include "src/geometry/nurbs_curve_2d.hpp"
#include "src/geometry/nurbs_curve_3d.hpp"
#include "src/geometry/nurbs_patch_triangulator_3d.hpp"
#include "src/geometry/nurbs_surface_3d.hpp"
#include "src/geometry/nurbs_utils.hpp"
#include "src/geometry/p2_curve_2d.hpp"
#include "src/geometry/p2_projection_2d.hpp"
#include "src/geometry/p2_projection_3d.hpp"
#include "src/geometry/p2_surface_3d.hpp"
