#pragma once

#include "src/local_cauchy/edge_patch_laplacian_3d.hpp"

#include "src/bulk_solvers/laplace_zfft_bulk_solver_2d.hpp"
#include "src/bulk_solvers/laplace_zfft_bulk_solver_3d.hpp"
#include "src/local_cauchy/edge_singular_bspline_fit_3d.hpp"
#include "src/local_cauchy/edge_singular_fit_3d.hpp"
#include "src/operators/laplace_bvp_2d.hpp"
#include "src/operators/laplace_bvp_3d.hpp"
#include "src/operators/laplace_neumann_exterior_trace_2d.hpp"
#include "src/operators/laplace_nsc_et_bvp_2d.hpp"
#include "src/operators/laplace_transmission_2d.hpp"
#include "src/operators/laplace_transmission_3d.hpp"
#include "src/potentials/laplace_potential.hpp"
#include "src/transfer/laplace_arc_length_bspline_crossing_jet_2d.hpp"
#include "src/transfer/laplace_nurbs_density_trace_state_2d.hpp"
#include "src/transfer/laplace_crossing_local_polynomial_2d.hpp"
#include "src/transfer/nurbs_density_space_2d.hpp"
#include "src/transfer/laplace_restrict_2d.hpp"
#include "src/transfer/laplace_restrict_3d.hpp"
#include "src/transfer/laplace_spread_2d.hpp"
#include "src/transfer/laplace_spread_3d.hpp"
